### ISSUE TITLE
Add support for UTF16 ranges or Unicode ranges

### ISSUE THREAD

**Issue by RunDevelopment** [2fd/rregex#31]
Hi!

I am using this library in a project and found that the `Match`es returned by `findAll` denote the start and end points in byte ranges (just like the underlying regex library). This is a problem, because JavaScript uses UTF16 to encode strings, which means that those byte ranges can't be used directly.

Could you please add a UTF16 version of this API or provide a way to convert between byte ranges and UTF16 ranges?

**Additional Information:**
Here's an example of why this is a problem. https://rregex.dev/?version=1.7.0&method=find&regex=.&text=%C3%A4%C3%B6%C3%BC
UTF8 needs 2 bytes to represent "ä", but the character fits within one UTF16 char code. So using JS to do `"äöü".slice(0, 2)` for the first match will return `aö` instead of `ä`.

**Alternatives:**
Another idea would be to provide Unicode ranges instead. Rust has `chars` and `char_indices` built in, so this might be easier to implement. This would still be more useable from the JS side of things.

I made simple Python bindings for Rust regex today and used this approach there. [This is the code I used to do the conversion](https://github.com/chaiNNer-org/chaiNNer-rs/blob/5fd7ffe0e42812f79a8024de367e7223bb9bbd96/crates/regex-py/src/position.rs#L23). Feel free to copy it and publish it under whatever license you want. You have my permission.

**Comment by 2fd** [comment]
Hi @RunDevelopment!

I understand what you are saying, but the library's objective is to execute the rust crate as faithfully as possible because it was intended to be used on the playground.

If you need to check what is the value of the slice, you could use the `value` prop of the `Match` object, or if for some reason you need to interact directly with the string in JS you can do it with the [`TextEncoder`](https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder) and [`TextDecoder`](https://developer.mozilla.org/en-US/docs/Web/API/TextDecoder) classes as [I do in the playground](https://github.com/2fd/rust-regex-playground/blob/5525cbfba207861e5e3cbce0810acd1f3915b989/src/rregex.ts#L107-L113)

```js
const buff = new TextEncoder().encode("äöü")
const slice = buff.slice(0, 2)
console.log(new TextDecoder().decode(slice)) // "ä"
```

If that isn't enough for your use case, we can discuss a better API that helps both.

**Comment by RunDevelopment** [comment]
I'm implementing a custom replace function, so `Match#value` isn't enough for me. 

Using `TextEncoder` and `TextDecoder` is a good idea, and I think I'll use that. Thank you.
